openapi: 3.2.0
info:
  title: Offer Tool Payment Options API
  description: Api definitions for Offer Tool
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Payment Options
paths:
  /api/v1/payment-options:
    get:
      operationId: GetAllPaymentOptionsController_handle_v1
      parameters: []
      responses:
        2XX:
          description: Return all payment options for the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllPaymentOptionsDtoResponse'
      tags:
      - Payment Options
      summary: Get all payment options controller handle v1
      x-summary-source: derived
components:
  schemas:
    GetAllPaymentOptionsDtoResponse:
      type: object
      properties:
        id:
          type: string
          description: The id of the payment option
        name:
          type: string
          description: The name of the payment option
      required:
      - id
      - name
