openapi: 3.2.0
info:
  title: Offer Tool Tenants API
  description: Api definitions for Offer Tool
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Tenants
paths:
  /api/v1/tenant:
    get:
      operationId: TenantController_getTenants_v1
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Tenants
      summary: Tenant controller get tenants v1
      x-summary-source: derived
  /api/v1/tenant/switch:
    post:
      operationId: TenantController_switchActiveTenant_v1
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SwitchTenantRequestDto'
      responses:
        '200':
          description: ''
      tags:
      - Tenants
      summary: Tenant controller switch active tenant v1
      x-summary-source: derived
components:
  schemas:
    SwitchTenantRequestDto:
      type: object
      properties:
        tenantId:
          type: string
          description: ID of the tenant to switch to
      required:
      - tenantId
