openapi: 3.2.0
info:
  title: Offer Tool Index API
  description: Api definitions for Offer Tool
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Index
paths:
  /:
    get:
      operationId: IndexController_index
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/'
      tags:
      - Index
      summary: Index controller index
      x-summary-source: derived
